server:
  port: 8080
  servlet.context-path: /minishop

spring:
  datasource:
    url: jdbc:mysql://47.103.202.12:3306/sys-minishop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid.filters: stat
    druid.maxActive: 20
    druid.initialSize: 1
    druid.maxWait: 60000
    druid.minIdle: 1
    druid.timeBetweenEvictionRunsMillis: 60000
    druid.minEvictableIdleTimeMillis: 300000
    druid.validationQuery: select 'x'
    druid.testWhileIdle: true
    druid.testOnBorrow: false
    druid.testOnReturn: false
    druid.poolPreparedStatements: true
    druid.maxOpenPreparedStatements: 20
  redis:
    host: 47.103.202.12
    port: 6379
    password: 123456
    timeout: 100ms
    lettuce:
      shutdown-timeout: 100ms
  mvc:
    static-path-pattern:
      - /static/**
      - /upload/**
  resources:
    static-locations:
      - /static/**
      - /upload/**

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cqut.minishop.entity
  configuration:
    cache-enabled: true
    multiple-result-sets-enabled: true
    default-executor-type: REUSE
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    default-statement-timeout: 25000

# 邮箱
spring.mail.host: smtp.163.com
spring.mail.username: yang13260906172@163.com
spring.mail.password: yang13260906172
spring.mail.default-encoding: UTF-8

mail.fromMail.addr: yang13260906172@163.com