server:
  port: 8080
  servlet.context-path: /minishop

spring:
  datasource:
    url: jdbc:mysql://47.103.202.12:3306/sys-minishop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid.filters: stat
    druid.maxActive: 20
    druid.initialSize: 1
    druid.maxWait: 60000
    druid.minIdle: 1
    druid.timeBetweenEvictionRunsMillis: 60000
    druid.minEvictableIdleTimeMillis: 300000
    druid.validationQuery: select 'x'
    druid.testWhileIdle: true
    druid.testOnBorrow: false
    druid.testOnReturn: false
    druid.poolPreparedStatements: true
    druid.maxOpenPreparedStatements: 20
  redis:
    host: 47.103.202.12
    port: 6379
    password: 123456
    timeout: 100ms
    lettuce:
      shutdown-timeout: 100ms


mybatis:
  mapper-locations: classpath:mapping/*.xml  #\u6CE8\u610F\uFF1A\u4E00\u5B9A\u8981\u5BF9\u5E94mapper\u6620\u5C04xml\u6587\u4EF6\u7684\u6240\u5728\u8DEF\u5F84
  type-aliases-package: com.cqut.minishop.entity  # \u6CE8\u610F\uFF1A\u5BF9\u5E94\u5B9E\u4F53\u7C7B\u7684\u8DEF\u5F84
  configuration:
    cache-enabled: true
    multiple-result-sets-enabled: true
    default-executor-type: REUSE
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    default-statement-timeout: 25000
